---
title: "Intro to R and R Markdown"
author: "Lauryn Howlett"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("SetupScript.R")
```

#### Lists

```{r}
myList <- list("apple", 1993, FALSE, penguins)
str(myList)
names(myList) <- c("fruit", "year", "logic", "data")
names(myList)
```

```{r}
# for lists we use double brackes [[]]
myList[[1]]

myList[["data"]]
```

#### Indexing

```{r}
# for vectors we use single brackets []
myVector <- c("apple", "banana", "pear")
myVector[2]
```

#### Filtering

```{r}
filter(penguins, species == "Adelie")

filter(penguins, species != "Adelie")

filter(penguins, island %in% c("Dream", "Torgersen") & !is.na(bill_length_mm))
```

#### Select

```{r}
# Select two specific variables
select(penguins, species, sex)

# Select a range of variables
select(penguins, species:flipper_length_mm)

# Rename columns within select
select(penguins, genus = species, island)


# Select column variables that are recorded in mm
select(penguins, contains("mm"))
```

**Create new variables with mutate()**

```{r}
# New variable that calculates bill length in cm
mutate(penguins, bill_length_cm = bill_length_mm/10)

# mutate based on conditional statements
mutate(penguins, species_sex = if_else(sex == 'male', paste0(species,"_m"), paste0(species, "_f")))
```
